FROM nginx

WORKDIR /usr/share/react

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs


COPY package*.json ./

RUN npm i --save --legacy-peer-deps

COPY . .

RUN npm run build

RUN rm -r /usr/share/nginx/html/*
RUN cp -a build/. /usr/share/nginx/html

